apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retreat-cart
  namespace: cicd
spec:
  project: default
  source:
    repoURL: git@github.com:polacojose/retreat-cart-deploy.git
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: retreat-cart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
