apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: retreat-cart
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: retreat-cart
          image: registry.polacoproject.net/retreat-cart:latest # kustomize will patch
          ports:
            - containerPort: 8000
          env:
            - name: RETREAT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: retreat-credentials
                  key: email
            - name: RETREAT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retreat-credentials
                  key: password
