apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retreat

resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
- service.yaml

labels:
- includeTemplates: true
- includeSelectors: true
  pairs:
    app: retreat-cart
images:
- name: registry.polacoproject.net/retreat-cart
  newTag: 2263b63
